theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
language: "<%= I18n.locale.to_s.split('-')[0].downcase %>"
theme_advanced_buttons3_add:
  - tablecontrols
  - fullscreen
  - fontsizeselect
toolbar:
  -  fontselect | fontsizeselect | bold | italic | underline | alignleft | aligncenter | alignjustify | alignright | image | link | uploadimage
plugins:
  - table
  - fullscreen
  - image
  - link
  - uploadimage
  
image_class_list:
  - title: 'Center'
    value: 'img-center'
  - title: 'Left thumbnail'
    value: 'img-left img-thumbnail'
  - title: 'Right thumbnail'
    value: 'img-right img-thumbnail'